# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history:
HISTCONTROL=ignoreboth:erasedups

# include a nice timestamp when printing commands history:
export HISTTIMEFORMAT="[%d-%m %T] "

# append to the history file, don't overwrite it:
shopt -s histappend

# Remember the history:
HISTSIZE=10000
HISTFILESIZE=20000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

function make_bash_prompt()
{
  local EXITCODE="$?"                 # This needs to be first.

  local colorNONE="\[\033[0m\]"       # resets color to terminal's FG color.
  local colorK="\[\033[0;30m\]"       # regular black
  local colorR="\[\033[0;31m\]"       # regular red
  local colorG="\[\033[0;32m\]"       # regular green
  local colorY="\[\033[0;33m\]"       # regular yellow
  local colorB="\[\033[0;34m\]"       # regular blue
  local colorM="\[\033[0;35m\]"       # regular magenta
  local colorC="\[\033[0;36m\]"       # regular cyan
  local colorW="\[\033[0;37m\]"       # regular white
  local colorKEM="\[\033[1;30m\]"     # bold black
  local colorREM="\[\033[1;31m\]"     # bold red
  local colorGEM="\[\033[1;32m\]"     # bold green
  local colorYEM="\[\033[1;33m\]"     # bold yellow
  local colorBEM="\[\033[1;34m\]"     # bold blue
  local colorMEM="\[\033[1;35m\]"     # bold magenta
  local colorCEM="\[\033[1;36m\]"     # bold cyan
  local colorWEM="\[\033[1;37m\]"     # bold white
  local bgcolorK="\[\033[40m\]"       # background black
  local bgcolorR="\[\033[41m\]"       # background red
  local bgcolorG="\[\033[42m\]"       # background green
  local bgcolorY="\[\033[43m\]"       # background yellow
  local bgcolorB="\[\033[44m\]"       # background blue
  local bgcolorM="\[\033[45m\]"       # background magenta
  local bgcolorC="\[\033[46m\]"       # background cyan
  local bgcolorW="\[\033[47m\]"       # background white

  local usercolor=$colorG    # normal user's color - green.
  if [ $UID -eq "0" ]; then
    usercolor=$colorR        # superuser's color - red.
  fi
  local exitcolor=$colorG    # normal exit color - green.
  if [ "$EXITCODE" -ne "0" ]; then
    exitcolor="$colorY"      # abnormal exit color - yellow.
  fi
  PS1="${colorNONE}[${exitcolor}$EXITCODE${colorNONE}] [${colorM}\t${colorNONE}] ${usercolor}\u${colorNONE} in ${colorB}\w ${usercolor}\n\$${colorNONE} "
}

PROMPT_COMMAND=make_bash_prompt

# colored GCC warnings and errors
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# Sources the common shell aliases:
if [ -f ~/.config/shrc/common.shrc ]; then
    . ~/.config/shrc/common.shrc
fi

# Sources the aliases for easier control of the package manager:
if [ -f ~/.config/shrc/package_manager.shrc ]; then
  . ~/.config/shrc/package_manager.shrc
fi

# Sources the machine-specific aliases:
if [ -f ~/.config/shrc/machine_specific.shrc ]; then
  . ~/.config/shrc/machine_specific.shrc
fi


# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi
