set nocompatible
set t_Co=256
set encoding=utf-8

execute pathogen#infect()
syntax on
set background=dark
colorscheme torte

set rtp+=$HOME/.local/lib/python2.7/site-packages/powerline/bindings/vim
set laststatus=2

if has("gui running")
  set lines=999 columns=999
endif

" Various non-bool options:
set history=512
set tabstop=2
set shiftwidth=2
set so=7
set backspace=eol,start,indent
set tabpagemax=50
set colorcolumn=80
set matchtime=7
highlight ColorColumn guibg=Black ctermbg=Black
highlight Search cterm=underline ctermbg=None ctermfg=Yellow
highlight MatchParen cterm=underline ctermbg=None ctermfg=Blue
" End of non-bool options.


" Key mappings:
let mapleader="\<Space>"
let g:mapleader="\<Space>"
let maplocalleader="\\"
nnoremap ; :
set pastetoggle=<F5>
nnoremap <Leader>w :w<CR>
nmap <Leader><Leader> V
map j gj
map k gk
nnoremap H g^
nnoremap L g$
vnoremap <silent> y y`]
vnoremap <silent> p p`]
nnoremap <silent> p p`]
nnoremap Q <nop>
map q: :q

" Easier reindenting of a visual selection: reselects a block after indent/outdent
vnoremap < <gv
vnoremap > >gv

"commands for quick .vimrc editing - <leader>ev and <leader>sv
nnoremap <leader>ev :vsplit $MYVIMRC<cr>
nnoremap <leader>sv :source $MYVIMRC<cr>

"commands for surrounding a word with various characters
nnoremap <leader>" viw<esc>a"<esc>hbi"<esc>lel
nnoremap <leader>' viw<esc>a'<esc>hbi'<esc>lel

" Switch off search highlight temporarily:
nnoremap <silent> <Leader>/ :nohlsearch<cr>

" Move a line of text using ALT+[jk]
nmap <M-j> mz:m+<cr>`z
nmap <M-k> mz:m-2<cr>`z
vmap <M-j> :m'>+<cr>`<my`>mzgv`yo`z
vmap <M-k> :m'<-2<cr>`>my`<mzgv`yo`z

" use the autocompletion: C-N ard C-P
map! ^P ^[a. ^[hbmmi?\<^[2h"zdt.@z^Mywmx`mP xi
map! ^N ^[a. ^[hbmmi/\<^[2h"zdt.@z^Mywmx`mP xi


" Abbreviations autoexpanding into useful info:
iabbrev @@ a.szczerbiak@samsung.com
iabbrev (@@ Adam Szczerbiak (a.szczerbiak@samsung.com)
iabbrev @@@ szczerbiakadam@gmail.com
iabbrev (@@@ Adam Szczerbiak (szczerbiakadam@gmail.com)
iabbrev spam@ asz101.allegro@gmail.com

" End of autoexpanding abbreviations.

" Functions:
function! InsertHtml5Boilerplate()
  " HTML5 boilerplate code: ~/.vim/snippets/html5.boilerplate
  r~/.vim/snippets/html5.boilerplate
endfunction

nnoremap <leader>H :call InsertHtml5Boilerplate()<CR>
" End of functions.

" Typo-s autofix:
iabbrev improt import
iabbrev sattic static
iabbrev mani main
iabbrev vodi void
iabbrev publci public
" End of typo-s autofixes.

runtime vimrc/autocommands.vimrcpart
runtime vimrc/common.vimrcpart
runtime vimrc/unlearning.vimrcpart
